import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layouts/Header";
import "@material/web/button/filled-button.js";
import "@material/web/button/outlined-button.js";
import "@material/web/checkbox/checkbox.js";
import { Toaster } from "react-hot-toast";
import { ClothesWrapper } from "@/context/clothes_context";
import { UserWrapper } from "@/context/user_context";

import CustomFooter from "@/components/general/footer";
import { Suspense } from "react";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ethrift app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {" "}
      <body className="bg-[#D9D9D9] pb-10 ">
        {" "}
        <UserWrapper>
          <ClothesWrapper>
            <Header />
            <Toaster position="bottom-right" />
            <Suspense fallback={<p>Loading feed...</p>}>
              <div className="mx-10">{children}</div>
            </Suspense>
          </ClothesWrapper>
        </UserWrapper>
      </body>
    </html>
  );
}
